# -*- coding: utf-8 -*-
# Copyright (C) 2004-2009 Tiny SPRL (<http://tiny.be>).
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Ascendia CRM-Project",
    "version": "10.0.1.0.0",
    "author": "Yunesky Del Rio",
    "category": "Project",
    "license": "AGPL-3",
    "website": "https://odoo-community.org/",
    "depends": ["base",
                "web",
                "calendar",
                "account",
                "crm",
                "sale",
                "purchase",
                "product",
                "project",
                "ascendia_project",
                "ascendia_crm",
                "ascendia_price_request",
                "ascendia_sales_proposal",
                "ascendia_training_credits"],
    "data": ['wizard/task_wizard_views.xml',
             'views/account_invoice_view.xml',
             'views/lead_view.xml',
             'views/res_partner_view.xml',
             'views/price_request_view.xml',
             'views/product_template_view.xml',
             'views/purchase_order_view.xml',
             'views/ascendia_training_credits_view.xml',
             'views/sale_order_view.xml',
             'views/sale_proposal_view.xml',
             'views/task_menu_items.xml',
             'views/task_view.xml',
             'views/calendar_event_view.xml'],
    'qweb': [
        "static/src/xml/task_menu.xml",
    ],
    "installable": True,
    "auto_install": False,
}
